任意のregistryのrepositoryにpush可能に

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,18 +1,23 @@
 #!/bin/bash
 
+if [ -n "$AUTH_DATA" ]; then
+  echo $AUTH_DATA > /root/.docker/config.json
+fi
+
 function abort
 {
    echo "$@" 1>&2
    exit 1
 }
 
-# REPO=${REGISTRY_PORT/tcp:\/\//}
-REPO=${REPO:-localhost:5000}
-NAME=${NAME:-storage}
+REGI=${REGI:-docker.io}
+[ "$REPO" ] || abort "REPO env is missing."
 [ "$TAG" ] || abort "TAG env is missing."
+NAME=$(mkpasswd -m md5 '' | base64 | sed 's/[=+\/]//g')
 
-docker run --name storage_$TAG --volumes-from $HOSTNAME subak/storage backup $@
-docker commit storage_$TAG $REPO/$NAME:$TAG
-docker push $REPO/$NAME:$TAG
-docker rm storage_$TAG
-docker rmi $REPO/$NAME:$TAG
+docker run --name $NAME --volumes-from $HOSTNAME subak/storage backup $@
+docker commit $NAME $REGI/$REPO:$TAG
+# TODO: handle unauthorized error
+docker push $REGI/$REPO:$TAG
+docker rm $NAME
+docker rmi $REGI/$REPO:$TAG
diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -1,16 +1,19 @@
 #!/bin/bash
 
+if [ -n "$AUTH_DATA" ]; then
+  echo $AUTH_DATA > /root/.docker/config.json
+fi
+
 function abort
 {
    echo "$@" 1>&2
    exit 1
 }
 
-# REPO=${REGISTRY_PORT/tcp:\/\//}
-REPO=${REPO:-localhost:5000}
-NAME=${NAME:-storage}
-[ $TAG ] || abort "TAG env is missing."
+REGI=${REGI:-docker.io}
+[ "$REPO" ] || abort "REPO env is missing."
+[ "$TAG" ] || abort "TAG env is missing."
 
-docker pull $REPO/$NAME:$TAG
-docker run --rm --volumes-from $HOSTNAME $REPO/$NAME:$TAG restore $@
-docker rmi $REPO/$NAME:$TAG
+docker pull $REGI/$REPO:$TAG
+docker run --rm --volumes-from $HOSTNAME $REGI/$REPO:$TAG restore $@
+docker rmi $REGI/$REPO:$TAG
